apiVersion: apps/v1
kind: Deployment
metadata:
  name: overnew-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overnew
  template:
    metadata:
      labels:
        app: overnew
    spec:
      containers:
      - name: django
        image: overnew:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: overnew-service
spec:
  type: NodePort
  selector:
    app: overnew
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
